import os
from flask import Blueprint, request, jsonify, render_template
from infrastructure.data import get_db
from infrastructure.api_clients import OpenWeatherAdapter
from application.services import WeatherService, AlertSystem
from application.auth_interfaces import USER_SCHEMA, LOGIN_SCHEMA, validate_schema
from domain.entities import User, WeatherLog

# Setup Blueprint
current_dir = os.path.dirname(os.path.abspath(__file__))
weather_bp = Blueprint(
    "weather", __name__,
    template_folder=os.path.abspath(os.path.join(current_dir, "templates"))
)

# Initialize System Components
# (In a larger app, use a proper Dependency Injection container)
alert_system = AlertSystem()
API_KEY = "75ae68e49b3f2913ea034331514183f3"

def get_configured_service(db):
    adapter = OpenWeatherAdapter(API_KEY)
    service = WeatherService(adapter, db)
    # Attach Observer
    service.attach(alert_system)
    return service

@weather_bp.route("/")
def index():
    return render_template("index.html")

@weather_bp.route("/weather")
def weather():
    return render_template("weather.html")

# Feature: User Registration
@weather_bp.route("/api/register", methods=["POST"])
def register():
    data = request.json
    db = next(get_db())

    # Validate schema
    if not validate_schema(data, USER_SCHEMA):
        return jsonify({"error": "Invalid input data"}), 400

    # Check if user exists
    existing = db.query(User).filter(User.username == data['username']).first()
    if existing:
        return jsonify({"error": "Username taken"}), 400

    new_user = User(
        username=data['username'],
        password=data['password'], # Plain text for this exam demo only!
        host_city=data['host_city']
    )
    db.add(new_user)
    db.commit()

    return jsonify({
        "message": "Registration successful",
        "user_id": new_user.user_id,
        "host_city": new_user.host_city
    })

# Feature: Login (Simple)
@weather_bp.route("/api/login", methods=["POST"])
def login():
    data = request.json

    # Validate schema
    if not validate_schema(data, LOGIN_SCHEMA):
        return jsonify({"error": "Invalid input data"}), 400

    db = next(get_db())

    user = db.query(User).filter(
        User.username == data['username'],
        User.password == data['password']
    ).first()

    if not user:
        return jsonify({"error": "Invalid credentials"}), 401

    return jsonify({
        "user_id": user.user_id,
        "username": user.username,
        "host_city": user.host_city
    })

@weather_bp.route("/api/weather", methods=["GET"])
def get_weather():
    city = request.args.get("city")
    user_id = request.args.get("user_id")

    if not city or not user_id:
        return jsonify({"error": "Missing city or user_id"}), 400

    try:
        db = next(get_db())
        service = get_configured_service(db)
        
        # This triggers Adapter, DB Logging, and Observer
        full_data = service.get_weather_process(city, int(user_id))
        
        # Append the alert generated by the observer
        full_data["system_alert"] = alert_system.latest_alert
        
        return jsonify(full_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@weather_bp.route("/api/history/<user_id>", methods=["GET"])
def get_history(user_id):
    db = next(get_db())
    # Feature: Individual History
    logs = db.query(WeatherLog).filter(
        WeatherLog.user_id == user_id
    ).order_by(WeatherLog.logged_at.desc()).all()
    
    history_data = [
        {
            "city": log.city,
            "temp": log.temperature,
            "condition": log.condition,
            "date": log.logged_at.strftime("%Y-%m-%d %H:%M")
        } for log in logs
    ]
    return jsonify(history_data)